meta_name: "Virtual Styler"
meta_title: "Virtual Styler - Your personalized interior design experience."
meta_description: "Transform your space with our interior design services. Our experienced team works closely with you to create a personalized and functional design that reflects your unique style. From traditional to modern, we offer a range of design options to suit your preferences. Contact us today to start creating the home of your dreams!"
meta_image: "cover.png" # should exist in `app/assets/images/`
